#pragma once
#ifndef FILE_SLIMENANO_VERSION_H
#    define FILE_SLIMENANO_API_H
#    define SLIMENANO_MATH_VERSION "1.0.0"
#    define SLIMENANO_UI_VERSION "1.0.0"
#    define SLIMENANO_EVENT_VERSION "1.0.0"
#    define SLIMENANO_SERIALIZATION_VERSION "1.0.0"
#endif //!FILE_SLIMENANO_VERSION_H