#pragma once
#ifndef FILE_SLIMENANO_SERIALIZATION_H
#define FILE_SLIMENANO_SERIALIZATION_H
#include <slimenano-api.h>

SLIMENANO_LIBRARIES_DECLARED(serialization);

#endif //!FILE_SLIMENANO_SERIALIZATION_H
